version: 2
jobs:
  build:
    working_directory: /go/src/github.com/reactiveops/rbac-lookup

    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"

    steps:
      - checkout
      - run: go mod download && go mod verify
      - run: go test -v ./lookup/...

  release:
    working_directory: /go/src/github.com/reactiveops/rbac-lookup

    docker:
      - image: goreleaser/goreleaser
        environment:
          GO111MODULE: "on"

    steps:
      - checkout
      - run: go mod download && go mod verify
      - run: goreleaser

workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
