version: 2
jobs:
  build:
    working_directory: /go/src/github.com/reactiveops/rbac-lookup

    docker:
      - image: circleci/golang:1.11

    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go test -v ./lookup/...

  release:
    working_directory: /go/src/github.com/reactiveops/rbac-lookup

    docker:
      - image: goreleaser/goreleaser

    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: goreleaser

workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
